function WriteLeftMenu(divID, aID, divClassName, aClassName)
{
document.write("<div id=\"divID24\" class=\"headerLeftMenuInActive\"><a id=\"aID24\" href=\"#\" OnMouseOver=\"link('_statsindex','index',this)\" class=\"leftMenuLinkHeadInActive\">Statistics</a></div>\n");
document.write("<div id='leftmenutree' class='treeLeftMenu'>\n");
var treeLeftMenu = new TreeClass('treeLeftMenu', false);
treeLeftMenu.setTreeHeightDelta(-205);
treeLeftMenu.m_iDefaultExpandedLevel = 1;treeLeftMenu.setExpandCollapseNames('Expand All','Collapse All');
treeLeftMenu.startTree( true );
  treeLeftMenu.startParentNode('Default mainpage','"#"','','../directoryBlue', { "onmouseover":"link('','../../index',this);" });
  treeLeftMenu.startParentNode('karel_h_doc','"#"','','../directoryBlue', { "onmouseover":"link('_dir','../../karel_h_doc/karel_h_doc0',this);" });
  treeLeftMenu.startParentNode('Structs','"#"','','../structsBlue');
  treeLeftMenu.addNode('s_box','"#"','','../struct', { "onmouseover":"link('_class','../../karel_h_doc/s_box0',this);" });
  treeLeftMenu.addNode('s_robot','"#"','','../struct', { "onmouseover":"link('_class','../../karel_h_doc/s_robot0',this);" });
  treeLeftMenu.addNode('s_world','"#"','','../struct', { "onmouseover":"link('_class','../../karel_h_doc/s_world0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Functions','"#"','','../functionsBlue');
  treeLeftMenu.addNode('areValid','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/areValid231090242',this);" });
  treeLeftMenu.addNode('areYouHere','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/areYouHere231090242',this);" });
  treeLeftMenu.addNode('avenues','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/avenues122',this);" });
  treeLeftMenu.addNode('beepers','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/beepers122',this);" });
  treeLeftMenu.addNode('beepersInBag','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/beepersInBag122',this);" });
  treeLeftMenu.addNode('beepersInBox','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/beepersInBox122',this);" });
  treeLeftMenu.addNode('checkBoxStatus','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/checkBoxStatus122',this);" });
  treeLeftMenu.addNode('checkRobotStatus','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/checkRobotStatus122',this);" });
  treeLeftMenu.addNode('close_World','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/close_World122',this);" });
  treeLeftMenu.addNode('closeBox','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/closeBox122',this);" });
  treeLeftMenu.addNode('clreol','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/clreol122',this);" });
  treeLeftMenu.addNode('clrscr','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/clrscr122',this);" });
  treeLeftMenu.addNode('create_Box','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/create_Box2515574380',this);" });
  treeLeftMenu.addNode('create_Robot','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/create_Robot2608232773',this);" });
  treeLeftMenu.addNode('create_World','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/create_World86138908',this);" });
  treeLeftMenu.addNode('debug_Robot','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/debug_Robot122',this);" });
  treeLeftMenu.addNode('debug_Robot_Off','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/debug_Robot_Off122',this);" });
  treeLeftMenu.addNode('debug_Robot_On','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/debug_Robot_On122',this);" });
  treeLeftMenu.addNode('delay','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/delay243606788',this);" });
  treeLeftMenu.addNode('face','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/face60979',this);" });
  treeLeftMenu.addNode('faceEast','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/faceEast122',this);" });
  treeLeftMenu.addNode('faceNorth','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/faceNorth122',this);" });
  treeLeftMenu.addNode('faceSouth','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/faceSouth122',this);" });
  treeLeftMenu.addNode('faceWest','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/faceWest122',this);" });
  treeLeftMenu.addNode('facing','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/facing60979',this);" });
  treeLeftMenu.addNode('facingEast','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/facingEast122',this);" });
  treeLeftMenu.addNode('facingNorth','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/facingNorth122',this);" });
  treeLeftMenu.addNode('facingSouth','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/facingSouth122',this);" });
  treeLeftMenu.addNode('facingWest','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/facingWest122',this);" });
  treeLeftMenu.addNode('fatal_Error','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/fatal_Error86138908',this);" });
  treeLeftMenu.addNode('frontIsClear','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/frontIsClear122',this);" });
  treeLeftMenu.addNode('get_Error','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/get_Error122',this);" });
  treeLeftMenu.addNode('get_World','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/get_World231090242',this);" });
  treeLeftMenu.addNode('gotoxy','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/gotoxy231090242',this);" });
  treeLeftMenu.addNode('has_BEEPER','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/has_BEEPER231090242',this);" });
  treeLeftMenu.addNode('has_BEEPERS','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/has_BEEPERS231090242',this);" });
  treeLeftMenu.addNode('has_BOX','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/has_BOX231090242',this);" });
  treeLeftMenu.addNode('has_Error','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/has_Error122',this);" });
  treeLeftMenu.addNode('has_HWALL','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/has_HWALL231090242',this);" });
  treeLeftMenu.addNode('has_ROBOT','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/has_ROBOT802104044',this);" });
  treeLeftMenu.addNode('has_slot','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/has_slot231090242',this);" });
  treeLeftMenu.addNode('has_VWALL','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/has_VWALL231090242',this);" });
  treeLeftMenu.addNode('isEmptyBox','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/isEmptyBox122',this);" });
  treeLeftMenu.addNode('leftIsClear','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/leftIsClear122',this);" });
  treeLeftMenu.addNode('move','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/move122',this);" });
  treeLeftMenu.addNode('nextToABeeper','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/nextToABeeper122',this);" });
  treeLeftMenu.addNode('nextToABox','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/nextToABox122',this);" });
  treeLeftMenu.addNode('nextToARobot','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/nextToARobot122',this);" });
  treeLeftMenu.addNode('openBox','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/openBox122',this);" });
  treeLeftMenu.addNode('pickBeeper','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/pickBeeper122',this);" });
  treeLeftMenu.addNode('pickBeeperFromBox','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/pickBeeperFromBox122',this);" });
  treeLeftMenu.addNode('pullBeeperFromBox','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/pullBeeperFromBox122',this);" });
  treeLeftMenu.addNode('pushBeeperIntoBox','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/pushBeeperIntoBox122',this);" });
  treeLeftMenu.addNode('putBeeper','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/putBeeper122',this);" });
  treeLeftMenu.addNode('putBeeperInBox','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/putBeeperInBox122',this);" });
  treeLeftMenu.addNode('read_World','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/read_World86138908',this);" });
  treeLeftMenu.addNode('remove_World','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/remove_World2680726270',this);" });
  treeLeftMenu.addNode('reset_World','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/reset_World122',this);" });
  treeLeftMenu.addNode('rightIsClear','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/rightIsClear122',this);" });
  treeLeftMenu.addNode('save_World','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/save_World86138908',this);" });
  treeLeftMenu.addNode('search_World','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/search_World802104044',this);" });
  treeLeftMenu.addNode('set_Error','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/set_Error60979',this);" });
  treeLeftMenu.addNode('set_Robot','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/set_Robot231090242',this);" });
  treeLeftMenu.addNode('set_Speed','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/set_Speed60979',this);" });
  treeLeftMenu.addNode('set_World','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/set_World802104044',this);" });
  treeLeftMenu.addNode('show_Board','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/show_Board252067370',this);" });
  treeLeftMenu.addNode('show_Error','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/show_Error86138908',this);" });
  treeLeftMenu.addNode('show_Screen','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/show_Screen246775574',this);" });
  treeLeftMenu.addNode('show_Text','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/show_Text86138908',this);" });
  treeLeftMenu.addNode('show_World','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/show_World122',this);" });
  treeLeftMenu.addNode('streets','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/streets122',this);" });
  treeLeftMenu.addNode('turnLeft','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/turnLeft122',this);" });
  treeLeftMenu.addNode('turnOff','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/turnOff122',this);" });
  treeLeftMenu.addNode('turnOn','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/turnOn122',this);" });
  treeLeftMenu.addNode('xAvenue','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/xAvenue122',this);" });
  treeLeftMenu.addNode('yStreet','"#"','','../function', { "onmouseover":"link('_member','../../karel_h_doc/yStreet122',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Attributes','"#"','','../attributesBlue');
  treeLeftMenu.addNode('baseDelay','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/baseDelay0',this);" });
  treeLeftMenu.addNode('box_now','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/box_now0',this);" });
  treeLeftMenu.addNode('debug_txt','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/debug_txt0',this);" });
  treeLeftMenu.addNode('error_code','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/error_code0',this);" });
  treeLeftMenu.addNode('error_txt','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/error_txt0',this);" });
  treeLeftMenu.addNode('has_debug','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/has_debug0',this);" });
  treeLeftMenu.addNode('has_Text','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/has_Text0',this);" });
  treeLeftMenu.addNode('message','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/message0',this);" });
  treeLeftMenu.addNode('msg_board','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/msg_board0',this);" });
  treeLeftMenu.addNode('msg_txt','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/msg_txt0',this);" });
  treeLeftMenu.addNode('robot_now','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/robot_now0',this);" });
  treeLeftMenu.addNode('stepDelay','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/stepDelay0',this);" });
  treeLeftMenu.addNode('world_now','"#"','','../variable', { "onmouseover":"link('_member','../../karel_h_doc/world_now0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Types','"#"','','../typesBlue');
  treeLeftMenu.addNode('box','"#"','','../type', { "onmouseover":"link('_member','../../karel_h_doc/box0',this);" });
  treeLeftMenu.addNode('ref_box','"#"','','../type', { "onmouseover":"link('_member','../../karel_h_doc/ref_box0',this);" });
  treeLeftMenu.addNode('ref_robot','"#"','','../type', { "onmouseover":"link('_member','../../karel_h_doc/ref_robot0',this);" });
  treeLeftMenu.addNode('ref_world','"#"','','../type', { "onmouseover":"link('_member','../../karel_h_doc/ref_world0',this);" });
  treeLeftMenu.addNode('robot','"#"','','../type', { "onmouseover":"link('_member','../../karel_h_doc/robot0',this);" });
  treeLeftMenu.addNode('world','"#"','','../type', { "onmouseover":"link('_member','../../karel_h_doc/world0',this);" });
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endTree();
treeLeftMenu.readStateFromCookie();
document.write("</div>\n");
document.write("<div class=\"paragraphLeftMenu\">Pages</div>\n");
document.write("<div id=\"divID143\" class=\"leftMenuTreeInActive\"><a id=\"aID143\" href=\"#\" OnMouseOver=\"link('_statsgeneral','stats_general',this)\" class=\"leftMenuLinkInActive\">General</a></div>\n");
document.write("<div id=\"divID144\" class=\"leftMenuTreeInActive\"><a id=\"aID144\" href=\"#\" OnMouseOver=\"link('_statsundoc','stats_undoc',this)\" class=\"leftMenuLinkInActive\">Undocumented</a></div>\n");
document.write("<div id=\"divID145\" class=\"leftMenuTreeInActive\"><a id=\"aID145\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_msg',this)\" class=\"leftMenuLinkInActive\">Msg-Messages</a></div>\n");
document.write("<div id=\"divID146\" class=\"leftMenuTreeInActive\"><a id=\"aID146\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_warn',this)\" class=\"leftMenuLinkInActive\">Msg-Warnings</a></div>\n");
document.write("<div id=\"divID147\" class=\"leftMenuTreeInActive\"><a id=\"aID147\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_err',this)\" class=\"leftMenuLinkInActive\">Msg-Errors</a></div>\n");
document.write("<div id=\"divID148\" class=\"leftMenuTreeInActive\"><a id=\"aID148\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_dbg',this)\" class=\"leftMenuLinkInActive\">Msg-Debug</a></div>\n");
if(divID != "" && aID != "")
{
  var elemDiv = document.getElementById(divID);
  var elemA = document.getElementById(aID);
  if (elemDiv != undefined && elemA != undefined ) { // this is needed to abvoid crashing js on some memberpages 
    elemDiv.className = divClassName;
    elemA.className = aClassName;
  }
}
}
