function WriteLeftMenu(divID, aID, divClassName, aClassName)
{
document.write("<div id=\"divID142\" class=\"headerLeftMenuInActive\"><a id=\"aID142\" href=\"#\" OnMouseOver=\"link('_dir','karel_h_doc0',this)\" class=\"leftMenuLinkHeadInActive\">karel_h_doc</a></div>\n");
document.write("<div id='leftmenutree' class='treeLeftMenu'>\n");
var treeLeftMenu = new TreeClass('treeLeftMenu', false);
treeLeftMenu.setTreeHeightDelta(-205);
treeLeftMenu.m_iDefaultExpandedLevel = 1;treeLeftMenu.setExpandCollapseNames('Expand All','Collapse All');
treeLeftMenu.startTree( true );
  treeLeftMenu.startParentNode('Default mainpage','"#"','','../common/directoryBlue', { "onmouseover":"link('','../index',this);" });
  treeLeftMenu.startParentNode('karel_h_doc','"#"','','../common/directoryBlue', { "onmouseover":"link('_dir','karel_h_doc0',this);" });
  treeLeftMenu.startParentNode('Structs','"#"','','../common/structsBlue');
  treeLeftMenu.addNode('s_box','"#"','','../common/struct', { "onmouseover":"link('_class','s_box0',this);" });
  treeLeftMenu.addNode('s_robot','"#"','','../common/struct', { "onmouseover":"link('_class','s_robot0',this);" });
  treeLeftMenu.addNode('s_world','"#"','','../common/struct', { "onmouseover":"link('_class','s_world0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Functions','"#"','','../common/functionsBlue');
  treeLeftMenu.addNode('areValid','"#"','','../common/function', { "onmouseover":"link('_member','areValid231090242',this);" });
  treeLeftMenu.addNode('areYouHere','"#"','','../common/function', { "onmouseover":"link('_member','areYouHere231090242',this);" });
  treeLeftMenu.addNode('avenues','"#"','','../common/function', { "onmouseover":"link('_member','avenues122',this);" });
  treeLeftMenu.addNode('beepers','"#"','','../common/function', { "onmouseover":"link('_member','beepers122',this);" });
  treeLeftMenu.addNode('beepersInBag','"#"','','../common/function', { "onmouseover":"link('_member','beepersInBag122',this);" });
  treeLeftMenu.addNode('beepersInBox','"#"','','../common/function', { "onmouseover":"link('_member','beepersInBox122',this);" });
  treeLeftMenu.addNode('checkBoxStatus','"#"','','../common/function', { "onmouseover":"link('_member','checkBoxStatus122',this);" });
  treeLeftMenu.addNode('checkRobotStatus','"#"','','../common/function', { "onmouseover":"link('_member','checkRobotStatus122',this);" });
  treeLeftMenu.addNode('close_World','"#"','','../common/function', { "onmouseover":"link('_member','close_World122',this);" });
  treeLeftMenu.addNode('closeBox','"#"','','../common/function', { "onmouseover":"link('_member','closeBox122',this);" });
  treeLeftMenu.addNode('clreol','"#"','','../common/function', { "onmouseover":"link('_member','clreol122',this);" });
  treeLeftMenu.addNode('clrscr','"#"','','../common/function', { "onmouseover":"link('_member','clrscr122',this);" });
  treeLeftMenu.addNode('create_Box','"#"','','../common/function', { "onmouseover":"link('_member','create_Box2515574380',this);" });
  treeLeftMenu.addNode('create_Robot','"#"','','../common/function', { "onmouseover":"link('_member','create_Robot2608232773',this);" });
  treeLeftMenu.addNode('create_World','"#"','','../common/function', { "onmouseover":"link('_member','create_World86138908',this);" });
  treeLeftMenu.addNode('debug_Robot','"#"','','../common/function', { "onmouseover":"link('_member','debug_Robot122',this);" });
  treeLeftMenu.addNode('debug_Robot_Off','"#"','','../common/function', { "onmouseover":"link('_member','debug_Robot_Off122',this);" });
  treeLeftMenu.addNode('debug_Robot_On','"#"','','../common/function', { "onmouseover":"link('_member','debug_Robot_On122',this);" });
  treeLeftMenu.addNode('delay','"#"','','../common/function', { "onmouseover":"link('_member','delay243606788',this);" });
  treeLeftMenu.addNode('face','"#"','','../common/function', { "onmouseover":"link('_member','face60979',this);" });
  treeLeftMenu.addNode('faceEast','"#"','','../common/function', { "onmouseover":"link('_member','faceEast122',this);" });
  treeLeftMenu.addNode('faceNorth','"#"','','../common/function', { "onmouseover":"link('_member','faceNorth122',this);" });
  treeLeftMenu.addNode('faceSouth','"#"','','../common/function', { "onmouseover":"link('_member','faceSouth122',this);" });
  treeLeftMenu.addNode('faceWest','"#"','','../common/function', { "onmouseover":"link('_member','faceWest122',this);" });
  treeLeftMenu.addNode('facing','"#"','','../common/function', { "onmouseover":"link('_member','facing60979',this);" });
  treeLeftMenu.addNode('facingEast','"#"','','../common/function', { "onmouseover":"link('_member','facingEast122',this);" });
  treeLeftMenu.addNode('facingNorth','"#"','','../common/function', { "onmouseover":"link('_member','facingNorth122',this);" });
  treeLeftMenu.addNode('facingSouth','"#"','','../common/function', { "onmouseover":"link('_member','facingSouth122',this);" });
  treeLeftMenu.addNode('facingWest','"#"','','../common/function', { "onmouseover":"link('_member','facingWest122',this);" });
  treeLeftMenu.addNode('fatal_Error','"#"','','../common/function', { "onmouseover":"link('_member','fatal_Error86138908',this);" });
  treeLeftMenu.addNode('frontIsClear','"#"','','../common/function', { "onmouseover":"link('_member','frontIsClear122',this);" });
  treeLeftMenu.addNode('get_Error','"#"','','../common/function', { "onmouseover":"link('_member','get_Error122',this);" });
  treeLeftMenu.addNode('get_World','"#"','','../common/function', { "onmouseover":"link('_member','get_World231090242',this);" });
  treeLeftMenu.addNode('gotoxy','"#"','','../common/function', { "onmouseover":"link('_member','gotoxy231090242',this);" });
  treeLeftMenu.addNode('has_BEEPER','"#"','','../common/function', { "onmouseover":"link('_member','has_BEEPER231090242',this);" });
  treeLeftMenu.addNode('has_BEEPERS','"#"','','../common/function', { "onmouseover":"link('_member','has_BEEPERS231090242',this);" });
  treeLeftMenu.addNode('has_BOX','"#"','','../common/function', { "onmouseover":"link('_member','has_BOX231090242',this);" });
  treeLeftMenu.addNode('has_Error','"#"','','../common/function', { "onmouseover":"link('_member','has_Error122',this);" });
  treeLeftMenu.addNode('has_HWALL','"#"','','../common/function', { "onmouseover":"link('_member','has_HWALL231090242',this);" });
  treeLeftMenu.addNode('has_ROBOT','"#"','','../common/function', { "onmouseover":"link('_member','has_ROBOT802104044',this);" });
  treeLeftMenu.addNode('has_slot','"#"','','../common/function', { "onmouseover":"link('_member','has_slot231090242',this);" });
  treeLeftMenu.addNode('has_VWALL','"#"','','../common/function', { "onmouseover":"link('_member','has_VWALL231090242',this);" });
  treeLeftMenu.addNode('isEmptyBox','"#"','','../common/function', { "onmouseover":"link('_member','isEmptyBox122',this);" });
  treeLeftMenu.addNode('leftIsClear','"#"','','../common/function', { "onmouseover":"link('_member','leftIsClear122',this);" });
  treeLeftMenu.addNode('move','"#"','','../common/function', { "onmouseover":"link('_member','move122',this);" });
  treeLeftMenu.addNode('nextToABeeper','"#"','','../common/function', { "onmouseover":"link('_member','nextToABeeper122',this);" });
  treeLeftMenu.addNode('nextToABox','"#"','','../common/function', { "onmouseover":"link('_member','nextToABox122',this);" });
  treeLeftMenu.addNode('nextToARobot','"#"','','../common/function', { "onmouseover":"link('_member','nextToARobot122',this);" });
  treeLeftMenu.addNode('openBox','"#"','','../common/function', { "onmouseover":"link('_member','openBox122',this);" });
  treeLeftMenu.addNode('pickBeeper','"#"','','../common/function', { "onmouseover":"link('_member','pickBeeper122',this);" });
  treeLeftMenu.addNode('pickBeeperFromBox','"#"','','../common/function', { "onmouseover":"link('_member','pickBeeperFromBox122',this);" });
  treeLeftMenu.addNode('pullBeeperFromBox','"#"','','../common/function', { "onmouseover":"link('_member','pullBeeperFromBox122',this);" });
  treeLeftMenu.addNode('pushBeeperIntoBox','"#"','','../common/function', { "onmouseover":"link('_member','pushBeeperIntoBox122',this);" });
  treeLeftMenu.addNode('putBeeper','"#"','','../common/function', { "onmouseover":"link('_member','putBeeper122',this);" });
  treeLeftMenu.addNode('putBeeperInBox','"#"','','../common/function', { "onmouseover":"link('_member','putBeeperInBox122',this);" });
  treeLeftMenu.addNode('read_World','"#"','','../common/function', { "onmouseover":"link('_member','read_World86138908',this);" });
  treeLeftMenu.addNode('remove_World','"#"','','../common/function', { "onmouseover":"link('_member','remove_World2680726270',this);" });
  treeLeftMenu.addNode('reset_World','"#"','','../common/function', { "onmouseover":"link('_member','reset_World122',this);" });
  treeLeftMenu.addNode('rightIsClear','"#"','','../common/function', { "onmouseover":"link('_member','rightIsClear122',this);" });
  treeLeftMenu.addNode('save_World','"#"','','../common/function', { "onmouseover":"link('_member','save_World86138908',this);" });
  treeLeftMenu.addNode('search_World','"#"','','../common/function', { "onmouseover":"link('_member','search_World802104044',this);" });
  treeLeftMenu.addNode('set_Error','"#"','','../common/function', { "onmouseover":"link('_member','set_Error60979',this);" });
  treeLeftMenu.addNode('set_Robot','"#"','','../common/function', { "onmouseover":"link('_member','set_Robot231090242',this);" });
  treeLeftMenu.addNode('set_Speed','"#"','','../common/function', { "onmouseover":"link('_member','set_Speed60979',this);" });
  treeLeftMenu.addNode('set_World','"#"','','../common/function', { "onmouseover":"link('_member','set_World802104044',this);" });
  treeLeftMenu.addNode('show_Board','"#"','','../common/function', { "onmouseover":"link('_member','show_Board252067370',this);" });
  treeLeftMenu.addNode('show_Error','"#"','','../common/function', { "onmouseover":"link('_member','show_Error86138908',this);" });
  treeLeftMenu.addNode('show_Screen','"#"','','../common/function', { "onmouseover":"link('_member','show_Screen246775574',this);" });
  treeLeftMenu.addNode('show_Text','"#"','','../common/function', { "onmouseover":"link('_member','show_Text86138908',this);" });
  treeLeftMenu.addNode('show_World','"#"','','../common/function', { "onmouseover":"link('_member','show_World122',this);" });
  treeLeftMenu.addNode('streets','"#"','','../common/function', { "onmouseover":"link('_member','streets122',this);" });
  treeLeftMenu.addNode('turnLeft','"#"','','../common/function', { "onmouseover":"link('_member','turnLeft122',this);" });
  treeLeftMenu.addNode('turnOff','"#"','','../common/function', { "onmouseover":"link('_member','turnOff122',this);" });
  treeLeftMenu.addNode('turnOn','"#"','','../common/function', { "onmouseover":"link('_member','turnOn122',this);" });
  treeLeftMenu.addNode('xAvenue','"#"','','../common/function', { "onmouseover":"link('_member','xAvenue122',this);" });
  treeLeftMenu.addNode('yStreet','"#"','','../common/function', { "onmouseover":"link('_member','yStreet122',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Attributes','"#"','','../common/attributesBlue');
  treeLeftMenu.addNode('baseDelay','"#"','','../common/variable', { "onmouseover":"link('_member','baseDelay0',this);" });
  treeLeftMenu.addNode('box_now','"#"','','../common/variable', { "onmouseover":"link('_member','box_now0',this);" });
  treeLeftMenu.addNode('debug_txt','"#"','','../common/variable', { "onmouseover":"link('_member','debug_txt0',this);" });
  treeLeftMenu.addNode('error_code','"#"','','../common/variable', { "onmouseover":"link('_member','error_code0',this);" });
  treeLeftMenu.addNode('error_txt','"#"','','../common/variable', { "onmouseover":"link('_member','error_txt0',this);" });
  treeLeftMenu.addNode('has_debug','"#"','','../common/variable', { "onmouseover":"link('_member','has_debug0',this);" });
  treeLeftMenu.addNode('has_Text','"#"','','../common/variable', { "onmouseover":"link('_member','has_Text0',this);" });
  treeLeftMenu.addNode('message','"#"','','../common/variable', { "onmouseover":"link('_member','message0',this);" });
  treeLeftMenu.addNode('msg_board','"#"','','../common/variable', { "onmouseover":"link('_member','msg_board0',this);" });
  treeLeftMenu.addNode('msg_txt','"#"','','../common/variable', { "onmouseover":"link('_member','msg_txt0',this);" });
  treeLeftMenu.addNode('robot_now','"#"','','../common/variable', { "onmouseover":"link('_member','robot_now0',this);" });
  treeLeftMenu.addNode('stepDelay','"#"','','../common/variable', { "onmouseover":"link('_member','stepDelay0',this);" });
  treeLeftMenu.addNode('world_now','"#"','','../common/variable', { "onmouseover":"link('_member','world_now0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Types','"#"','','../common/typesBlue');
  treeLeftMenu.addNode('box','"#"','','../common/type', { "onmouseover":"link('_member','box0',this);" });
  treeLeftMenu.addNode('ref_box','"#"','','../common/type', { "onmouseover":"link('_member','ref_box0',this);" });
  treeLeftMenu.addNode('ref_robot','"#"','','../common/type', { "onmouseover":"link('_member','ref_robot0',this);" });
  treeLeftMenu.addNode('ref_world','"#"','','../common/type', { "onmouseover":"link('_member','ref_world0',this);" });
  treeLeftMenu.addNode('robot','"#"','','../common/type', { "onmouseover":"link('_member','robot0',this);" });
  treeLeftMenu.addNode('world','"#"','','../common/type', { "onmouseover":"link('_member','world0',this);" });
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endTree();
treeLeftMenu.readStateFromCookie();
document.write("</div>\n");
if(divID != "" && aID != "")
{
  var elemDiv = document.getElementById(divID);
  var elemA = document.getElementById(aID);
  if (elemDiv != undefined && elemA != undefined ) { // this is needed to abvoid crashing js on some memberpages 
    elemDiv.className = divClassName;
    elemA.className = aClassName;
  }
}
}
