function WriteLeftMenu(divID, aID, divClassName, aClassName)
{
document.write("<div id=\"divID0\" class=\"headerLeftMenuInActive\"><a id=\"aID0\" href=\"#\" OnMouseOver=\"link('','index',this)\" class=\"leftMenuLinkHeadInActive\">Default mainpage</a></div>\n");
document.write("<div id='leftmenutree' class='treeLeftMenu'>\n");
var treeLeftMenu = new TreeClass('treeLeftMenu', false);
treeLeftMenu.setTreeHeightDelta(-205);
treeLeftMenu.m_iDefaultExpandedLevel = 1;treeLeftMenu.setExpandCollapseNames('Expand All','Collapse All');
treeLeftMenu.startTree( true );
  treeLeftMenu.startParentNode('Default mainpage','"#"','','common/directoryBlue', { "onmouseover":"link('','index',this);" });
  treeLeftMenu.startParentNode('karel_h_doc','"#"','','common/directoryBlue', { "onmouseover":"link('_dir','karel_h_doc/karel_h_doc0',this);" });
  treeLeftMenu.startParentNode('Structs','"#"','','common/structsBlue');
  treeLeftMenu.addNode('s_box','"#"','','common/struct', { "onmouseover":"link('_class','karel_h_doc/s_box0',this);" });
  treeLeftMenu.addNode('s_robot','"#"','','common/struct', { "onmouseover":"link('_class','karel_h_doc/s_robot0',this);" });
  treeLeftMenu.addNode('s_world','"#"','','common/struct', { "onmouseover":"link('_class','karel_h_doc/s_world0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Functions','"#"','','common/functionsBlue');
  treeLeftMenu.addNode('areValid','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/areValid231090242',this);" });
  treeLeftMenu.addNode('areYouHere','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/areYouHere231090242',this);" });
  treeLeftMenu.addNode('avenues','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/avenues122',this);" });
  treeLeftMenu.addNode('beepers','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/beepers122',this);" });
  treeLeftMenu.addNode('beepersInBag','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/beepersInBag122',this);" });
  treeLeftMenu.addNode('beepersInBox','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/beepersInBox122',this);" });
  treeLeftMenu.addNode('checkBoxStatus','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/checkBoxStatus122',this);" });
  treeLeftMenu.addNode('checkRobotStatus','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/checkRobotStatus122',this);" });
  treeLeftMenu.addNode('close_World','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/close_World122',this);" });
  treeLeftMenu.addNode('closeBox','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/closeBox122',this);" });
  treeLeftMenu.addNode('clreol','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/clreol122',this);" });
  treeLeftMenu.addNode('clrscr','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/clrscr122',this);" });
  treeLeftMenu.addNode('create_Box','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/create_Box2515574380',this);" });
  treeLeftMenu.addNode('create_Robot','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/create_Robot2608232773',this);" });
  treeLeftMenu.addNode('create_World','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/create_World86138908',this);" });
  treeLeftMenu.addNode('debug_Robot','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/debug_Robot122',this);" });
  treeLeftMenu.addNode('debug_Robot_Off','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/debug_Robot_Off122',this);" });
  treeLeftMenu.addNode('debug_Robot_On','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/debug_Robot_On122',this);" });
  treeLeftMenu.addNode('delay','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/delay243606788',this);" });
  treeLeftMenu.addNode('face','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/face60979',this);" });
  treeLeftMenu.addNode('faceEast','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/faceEast122',this);" });
  treeLeftMenu.addNode('faceNorth','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/faceNorth122',this);" });
  treeLeftMenu.addNode('faceSouth','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/faceSouth122',this);" });
  treeLeftMenu.addNode('faceWest','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/faceWest122',this);" });
  treeLeftMenu.addNode('facing','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/facing60979',this);" });
  treeLeftMenu.addNode('facingEast','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/facingEast122',this);" });
  treeLeftMenu.addNode('facingNorth','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/facingNorth122',this);" });
  treeLeftMenu.addNode('facingSouth','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/facingSouth122',this);" });
  treeLeftMenu.addNode('facingWest','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/facingWest122',this);" });
  treeLeftMenu.addNode('fatal_Error','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/fatal_Error86138908',this);" });
  treeLeftMenu.addNode('frontIsClear','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/frontIsClear122',this);" });
  treeLeftMenu.addNode('get_Error','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/get_Error122',this);" });
  treeLeftMenu.addNode('get_World','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/get_World231090242',this);" });
  treeLeftMenu.addNode('gotoxy','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/gotoxy231090242',this);" });
  treeLeftMenu.addNode('has_BEEPER','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/has_BEEPER231090242',this);" });
  treeLeftMenu.addNode('has_BEEPERS','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/has_BEEPERS231090242',this);" });
  treeLeftMenu.addNode('has_BOX','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/has_BOX231090242',this);" });
  treeLeftMenu.addNode('has_Error','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/has_Error122',this);" });
  treeLeftMenu.addNode('has_HWALL','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/has_HWALL231090242',this);" });
  treeLeftMenu.addNode('has_ROBOT','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/has_ROBOT802104044',this);" });
  treeLeftMenu.addNode('has_slot','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/has_slot231090242',this);" });
  treeLeftMenu.addNode('has_VWALL','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/has_VWALL231090242',this);" });
  treeLeftMenu.addNode('isEmptyBox','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/isEmptyBox122',this);" });
  treeLeftMenu.addNode('leftIsClear','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/leftIsClear122',this);" });
  treeLeftMenu.addNode('move','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/move122',this);" });
  treeLeftMenu.addNode('nextToABeeper','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/nextToABeeper122',this);" });
  treeLeftMenu.addNode('nextToABox','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/nextToABox122',this);" });
  treeLeftMenu.addNode('nextToARobot','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/nextToARobot122',this);" });
  treeLeftMenu.addNode('openBox','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/openBox122',this);" });
  treeLeftMenu.addNode('pickBeeper','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/pickBeeper122',this);" });
  treeLeftMenu.addNode('pickBeeperFromBox','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/pickBeeperFromBox122',this);" });
  treeLeftMenu.addNode('pullBeeperFromBox','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/pullBeeperFromBox122',this);" });
  treeLeftMenu.addNode('pushBeeperIntoBox','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/pushBeeperIntoBox122',this);" });
  treeLeftMenu.addNode('putBeeper','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/putBeeper122',this);" });
  treeLeftMenu.addNode('putBeeperInBox','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/putBeeperInBox122',this);" });
  treeLeftMenu.addNode('read_World','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/read_World86138908',this);" });
  treeLeftMenu.addNode('remove_World','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/remove_World2680726270',this);" });
  treeLeftMenu.addNode('reset_World','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/reset_World122',this);" });
  treeLeftMenu.addNode('rightIsClear','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/rightIsClear122',this);" });
  treeLeftMenu.addNode('save_World','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/save_World86138908',this);" });
  treeLeftMenu.addNode('search_World','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/search_World802104044',this);" });
  treeLeftMenu.addNode('set_Error','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/set_Error60979',this);" });
  treeLeftMenu.addNode('set_Robot','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/set_Robot231090242',this);" });
  treeLeftMenu.addNode('set_Speed','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/set_Speed60979',this);" });
  treeLeftMenu.addNode('set_World','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/set_World802104044',this);" });
  treeLeftMenu.addNode('show_Board','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/show_Board252067370',this);" });
  treeLeftMenu.addNode('show_Error','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/show_Error86138908',this);" });
  treeLeftMenu.addNode('show_Screen','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/show_Screen246775574',this);" });
  treeLeftMenu.addNode('show_Text','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/show_Text86138908',this);" });
  treeLeftMenu.addNode('show_World','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/show_World122',this);" });
  treeLeftMenu.addNode('streets','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/streets122',this);" });
  treeLeftMenu.addNode('turnLeft','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/turnLeft122',this);" });
  treeLeftMenu.addNode('turnOff','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/turnOff122',this);" });
  treeLeftMenu.addNode('turnOn','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/turnOn122',this);" });
  treeLeftMenu.addNode('xAvenue','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/xAvenue122',this);" });
  treeLeftMenu.addNode('yStreet','"#"','','common/function', { "onmouseover":"link('_member','karel_h_doc/yStreet122',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Attributes','"#"','','common/attributesBlue');
  treeLeftMenu.addNode('baseDelay','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/baseDelay0',this);" });
  treeLeftMenu.addNode('box_now','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/box_now0',this);" });
  treeLeftMenu.addNode('debug_txt','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/debug_txt0',this);" });
  treeLeftMenu.addNode('error_code','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/error_code0',this);" });
  treeLeftMenu.addNode('error_txt','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/error_txt0',this);" });
  treeLeftMenu.addNode('has_debug','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/has_debug0',this);" });
  treeLeftMenu.addNode('has_Text','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/has_Text0',this);" });
  treeLeftMenu.addNode('message','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/message0',this);" });
  treeLeftMenu.addNode('msg_board','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/msg_board0',this);" });
  treeLeftMenu.addNode('msg_txt','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/msg_txt0',this);" });
  treeLeftMenu.addNode('robot_now','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/robot_now0',this);" });
  treeLeftMenu.addNode('stepDelay','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/stepDelay0',this);" });
  treeLeftMenu.addNode('world_now','"#"','','common/variable', { "onmouseover":"link('_member','karel_h_doc/world_now0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Types','"#"','','common/typesBlue');
  treeLeftMenu.addNode('box','"#"','','common/type', { "onmouseover":"link('_member','karel_h_doc/box0',this);" });
  treeLeftMenu.addNode('ref_box','"#"','','common/type', { "onmouseover":"link('_member','karel_h_doc/ref_box0',this);" });
  treeLeftMenu.addNode('ref_robot','"#"','','common/type', { "onmouseover":"link('_member','karel_h_doc/ref_robot0',this);" });
  treeLeftMenu.addNode('ref_world','"#"','','common/type', { "onmouseover":"link('_member','karel_h_doc/ref_world0',this);" });
  treeLeftMenu.addNode('robot','"#"','','common/type', { "onmouseover":"link('_member','karel_h_doc/robot0',this);" });
  treeLeftMenu.addNode('world','"#"','','common/type', { "onmouseover":"link('_member','karel_h_doc/world0',this);" });
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endTree();
treeLeftMenu.readStateFromCookie();
document.write("</div>\n");
document.write("<div class=\"paragraphLeftMenu\">Miscellaneous</div>\n");
document.write("<div id=\"divID24\" class=\"leftMenuTreeInActive\"><a id=\"aID24\" href=\"#\" OnMouseOver=\"link('_statsindex','common/statistics/index',this)\" class=\"leftMenuLinkInActive\">Statistics</a></div>\n");
if(divID != "" && aID != "")
{
  var elemDiv = document.getElementById(divID);
  var elemA = document.getElementById(aID);
  if (elemDiv != undefined && elemA != undefined ) { // this is needed to abvoid crashing js on some memberpages 
    elemDiv.className = divClassName;
    elemA.className = aClassName;
  }
}
}
